modLoader = "javafml"
loaderVersion = "[43,)"
license = "GPLV3"

[[mods]]
modId = "h_plus"
version = "1.0.1"
displayName = "H+"
logoFile = "logo.png"
authors = "Mr.Toad"
description ='''
Improves hardcore mod, adds new mobs, new mob functionsa and features.
Everything for hardcore you!
'''

[[dependencies.h_plus]]
modId = "forge"
mandatory = true
versionRange = "[45.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.h_plus]]
modId = "toadlib"
mandatory = true
versionRange = "[1.1.0,)"
ordering = "NONE"
side = "BOTH"

